package generator

import "google.golang.org/protobuf/compiler/protogen"

// GenerateHeader создает стандартный заголовок файла
func GenerateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-etcd. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
}
