// Code generated by protoc-gen-etcd. DO NOT EDIT.
package proto

import (
	context "context"
	json "encoding/json"
)

import (
	"context"
	"fmt"
	"go.etcd.io/etcd/client/v3"
	"time"
)

const (
	serviceNamePrefix = "/forms"
)

// EtcdClient предоставляет методы для работы с etcd
type EtcdClient struct {
	client *clientv3.Client
}

type EtcdConfig struct {
	Endpoints   []string
	DialTimeout int64
	Username    string
	Password    string
}

func NewEtcdClient(cfg *EtcdConfig) (*EtcdClient, error) {
	if cfg == nil {
		return fmt.Errorf("empty config")
	}

	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   cfg.Endpoints,
		DialTimeout: cfg.DialTimeout,
		Username:    cfg.Username,
		Password:    cfg.Password,
	})
	if err != nil {
		return nil, err
	}
	return &EtcdClient{client: cli}, nil
}

func (c *EtcdClient) GetLimitsKey(ctx context.Context, rq *LimitsKeyRequest) (resp *LimitsValue, err error) {
	key := fmt.Sprintf("/forms/config/%s/%s/limits", rq.PsCode, rq.Type)
	resp, err := c.client.Get(ctx, key)
	if err != nil {
		return nil, err
	}

	if len(resp.Kvs) == 0 {
		return nil, fmt.Errorf("key not found")
	}

	for _, v := range resp.Kvs {
		err = json.Unmarshal(v.Value, resp)
		if err != nil {
			return nil, err
		}
		return resp, nil
	}
	return resp, err
}
